source "https://rubygems.org"
ruby '2.5.1'
gem 'rubocop', '~> 0.57.2'
gem 'pry'
gem 'bundler'
gem 'json'
gem "nokogiri"
gem 'google_drive'
gem 'csv'
gem 'gem-release'
gem 'coveralls'
gem 'gmail_xoauth'
gem 'gmail'
gem 'twitter'
gem 'dotenv'
